### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by kkpwn** [sealindx/sproto-ts#1]
你好，我不知怎么联系你，只能在这里发个 issue，请见谅。
我在 《自己动手构造编译系统》作者的github中看到你提的 issue，应该已经测试demo成功了，我想问一下的系统环境，我使用ubuntu 18.04 x86 gcc-5 编译通过，但运行 test 时却提示 “段错误”，希望你能在百忙之中给一下指导，分享你的系统环境，小白感激不尽。

$uname -a:
Linux ubuntu 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by OneTrainee** [comment]
> 
> 
> 你好，我不知怎么联系你，只能在这里发个 issue，请见谅。
> 我在 《自己动手构造编译系统》作者的github中看到你提的 issue，应该已经测试demo成功了，我想问一下的系统环境，我使用ubuntu 18.04 x86 gcc-5 编译通过，但运行 test 时却提示 “段错误”，希望你能在百忙之中给一下指导，分享你的系统环境，小白感激不尽。
Linux ubuntu 4.18.0-25-generic #26~18.04.1-Ubuntu SMP Thu Jun 27 07:28:31 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kkpwn** [comment]
已经解决了，打扰了。
